ci:
  autoupdate_schedule: quarterly
  skip: [phpcbf, phpcs]
repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.5.2
    hooks:
      - id: biome-check
  - repo: local
    hooks:
      - id: phpcbf
        name: phpcbf
        entry: vendor/bin/phpcbf
        language: system
        types: [php]
      - id: phpcs
        name: phpcs
        entry: vendor/bin/phpcs
        language: system
        types: [php]
      - id: check-assets
        name: check-assets
        entry: script/check-assets
        language: system
        pass_filenames: false
        always_run: true
